version: '3.8'

services:
  mariadb:
    container_name: mariadb
    restart: always
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    restart: always
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html #i think i need to copy the static files inside the volume from the dockerfile
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  nginx:
    container_name: nginx
    restart: always
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
  redis:
    container_name: redis
    build: bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  adminer:
    build: bonus/adminer
    container_name: adminer
    restart: always
    networks:
      - inception_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:

networks:
  inception_network:
    driver: bridge
