version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - ${VOLUME_ROOT}:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    restart: always
    build: requirements/wordpress
    volumes:
      - ${VOLUME_ROOT}:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    restart: always
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ${VOLUME_ROOT}:/var/www/html
      - ${VOLUME_ROOT}:/etc/ssl/certs
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
  redis:
    container_name: redis
    build: bonus/redis
    restart: always
    ports:
     - '6379:6379'
    volumes:
      - ${VOLUME_ROOT}:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
  adminer:
    container_name: adminer
    build: bonus/adminer
    restart: always
    networks:
      - inception_network
    volumes:
      - ${VOLUME_ROOT}:/var/www/html
    depends_on:
      - mariadb
      - wordpress
  ftp:
    container_name: ftp
    build: bonus/ftp
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - inception_network
    volumes:
      - ${VOLUME_ROOT}:/var/www/html
      - ${VOLUME_ROOT}:/etc/ssl/certs
    env_file:
      - .env
  nextjs:
    container_name: nextjs
    build: bonus/nextjs
    restart: always
    ports:
      - "3000:3000"
    networks:
      - inception_network
    env_file:
      - .env
  cadvisor:
    container_name: cadvisor
    build: bonus/cAdvisor/
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - inception_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro


volumes:
  db_data:
  wordpress_data:
  cert_data:

networks:
  inception_network:
    driver: bridge
