version: '3.8'

services:
  mariadb:
    restart: always
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
# i will need to remove ports because i dont need to be open to the extern but only to the network
    ports:
      - "3306:3306"
    env_file:
      - .env
  wordpress:
    restart: always
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html #i think i need to copy the static files inside the volume from the dockerfile
    networks:
      - db_network
    env_file:
      - .env
    depends_on:
      - mariadb
volumes:
  db_data:
  wordpress_data:

networks:
  db_network:
    driver: bridge
