version: '3.8'

services:
  mariadb:
    container_name: mariadb
    restart: always
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    restart: always
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html #i think i need to copy the static files inside the volume from the dockerfile
    networks:
      - db_network
    env_file:
      - .env
    depends_on:
      - mariadb
volumes:
  db_data:
  wordpress_data:

networks:
  db_network:
    driver: bridge
