version: '3.8'

services:
   mariadb:
    build: services/db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    ports:
      - "3306:3306"
    env_file:
      - .env

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
