version: '3.8'

services:
  db:
    build: ./services/db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: passwordboii
      MYSQL_DATABASE: wordpress
      MYSQL_USER: rileone
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
